### ISSUE TITLE
Implement OrientationChanged listener which speaks

### ISSUE THREAD

**Issue by vontell** [ama-csail/AMA-Library#4]
Implement the `attachOrientationListener()` method which speaks when the orientation of the device changes. This method can be found [here](https://github.com/ama-csail/AMA-Library/blob/master/ama/src/main/java/edu/mit/dig/ama/features/Core.java#L19).

**Comment by vontell** [comment]
I realized that we cannot set this listener on the activity after creation. Therefore, we now have a new Activity for this feature, `AccessibleAppCompatActivity`

**Comment by williamcaruso** [comment]
Nice!
